version: 2.1 # Use 2.1 to enable using orbs and other features.

orbs:
  php: circleci/php@1.1.0

jobs:
  test:
    parameters:
      version:
        default: "8.0"
        description: PHP version to install
        type: string
    docker:
      - image: cimg/php:<<parameters.version>>
    steps:
      - checkout
      - php/install-composer
      - run: composer self-update

      # Print php and composer versions for debugging
      - run: php --version
      - run: composer --version

      # although not recommended, we need to update dependencies to work on php8.1
      - when:
          condition:
            equal: ["8.1", <<parameters.version>>]
          steps:
            - run: composer update

      # install deps
      - run: composer install

      # run tests
      - run:
          name: PHPUnit Tests
          command: vendor/bin/phpunit
 
workflows:
  version: 2
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - "8.0"
                - "8.1"
